version: 2

sources:
  - name: raw
    description: A snowflake db
    database: CORTEX_ANALYST_DEMO
    schema: REVENUE_TIMESERIES
    tables:
      - name: orders_raw
        description: Order Staging table
        columns:
          - name: order_id
            tests:
              - unique
              - not_null